pretrained_base_model_path: './pretrained_weights/sd-image-variations-diffusers'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
vae_path: './pretrained_weights/sd-vae-ft-mse'

denoising_unet_path: "./pretrained_weights/personalive/denoising_unet.pth"

inference_config: "configs/inference/inference_stage3.yaml"
weight_dtype: 'fp16'

# Test cases for photo-based inference
# Format: reference_image_path: [driving_image_path1, driving_image_path2, ...]
test_cases:
  'demo/ref_image_2.png':
  - 'demo/driving_image.png'
